import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
//import HeaderMobile from "@/components/header-mobile";
import Header from "@/components/header";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// const pacifico = Pacifico({
//   variable: "--font-pacifico",
//   subsets: ["latin"],
//   weight: "400",
// });

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className = {`bg-white ${inter.className}`}
      >
        <div className="flex">
          <Header />
          {/* <HeaderMobile /> */}
        </div>
        {children}
      </body>
    </html>
  );
}
